### PR TITLE
Move fastroute to suggestion

### PR DESCRIPTION
**Pull request by tyx**
As it is not mandatory to use aerys

### CODE REVIEW

**Comment by kelunik** [comment]
Suggested packages are horrible, because they don't allow defining compatible version constraints. I'd rather move the router out to a separate package than moving the dependency into "suggest".

**Comment by bwoebi** [comment]
Is there any win in not requiring FastRoute?
I think the Router is a pretty central feature, I'd dislike to move out. Sure, you may use your own router, but it'll probably be used by many.

**Comment by tyx** [comment]
IMO any current application get already a router. (this our case). So we want to use aerys but we will keep routing stuff in our side.

**Comment by kelunik** [comment]
Using your own router is perfectly fine, why do we need to make FastRoute optional for that?

**Comment by tyx** [comment]
Because I like to install only what I really need.

But not a big deal, I was just thinking it was a small mistake so here is the PR. I will use a composer workaround to avoid to install fastroute.

**Comment by kelunik** [comment]
@bwoebi What do you think about moving the router to a separate package?

**Comment by staabm** [comment]
wouldnt it be a single file repos?

**Comment by kelunik** [comment]
@staabm Basically, yes. But only due to `FastRoute` containing everything that's needed already.

**Comment by rdlowrey** [comment]
I'm personally in favor of splitting out the router into its own component library.

**Comment by bwoebi** [comment]
I personally consider it a _deterrent_ when I have to first find a shitton of mircocomponents to even start at all…

**Comment by bwoebi** [comment]
Never heard of that; I personally never use these composer commands though, but directly edit the json file always.
In this case it may be acceptable though.

**Comment by kelunik** [comment]
> I personally consider it a deterrent when I have to first find a shitton of mircocomponents to even start at all…

Everything not having external dependencies is fine. I wouldn't split the document root handler out, as that doesn't have any external dependencies on its own.

> But not a big deal, I was just thinking it was a small mistake so here is the PR. I will use a composer workaround to avoid to install fastroute.

@tyx Could you share your workaround? I actually want something similar to exclude all the polyfills in packages that require PHP 7 or even 7.1.

**Comment by tyx** [comment]
In your composer.json:

```
"replace": {
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*"
}
``` 

I don't know if it will continue to work in the next composer release, I hope so as it is very useful currently !

**Comment by kelunik** [comment]
Didn't know about `"replace"`, thanks! Works like a charm.

```json
"replace": {
    "symfony/polyfill-util": "*",
    "symfony/polyfill-php56": "*",
    "paragonie/random_compat": "*"
}
```

**Pull request closed without merging**
