### PR TITLE
Simplify CPU counter to use nproc

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by bwoebi** [comment]
Is this available on all distros?

**Comment by kelunik** [comment]
I'm not sure on that, but as it's on coreutils as you say, it should be fine.

**Comment by kelunik** [comment]
A advantage of `nproc` is that it shows the count of processors available to the process instead of the total installed number.

**Comment by bwoebi** [comment]
Well, for example it is not included with busybox … Well, I'm not sure, I let you decide whether to merge.

**Comment by lt** [comment]
While detecting available processors rather than installed processors seems to make perfect sense, I'm not sure I've ever seen a scenario where processors have been deliberately taken offline (which is what I believe is being catered for with nproc, rather than some kind of software limitation on processor usage)

**Comment by staabm** [comment]
any hyperthreading related things we need to consider?

**Comment by morrisonlevi** [comment]
All processors are routinely not available inside of cgroups and cpusets. I believe in the former case that `nproc` it works but I have no idea about the second.

**Comment by lt** [comment]
```
$ nproc
8
$ docker exec -ti test nproc
7
```
@morrisonlevi is right :)

**Comment by bwoebi** [comment]
Fine, merging that for now, when it explodes somewhere, we can still revert it.

**Comment by kelunik** [comment]
@morrisonlevi @lt Is it a good thing to rely on `nproc` then? I guess so?

**Pull request merged**
