### PR TITLE
Throw error if config file returned no hosts

### LINKED ISSUE #157: Useful error message for no hosts returned from config file
If no hosts are returned from the config file, Aerys currently fails with `[2017-07-25 12:05:12] critical TypeError: Expected an array of Hosts as second parameter, but array also contains integer in /home/kelunik/GitHub/kelunik/chat/vendor/amphp/aerys/lib/functions.php:541`, which is not really a helpful error message.

### PR DESCRIPTION
**Pull request by maxmeijer42**
Closes #157

### CODE REVIEW

**Comment by kelunik** [comment]
Why did you close your PRs?

**Comment by maxmeijer42** [comment]
Because I discovered hacktoberfest only starts at October 1, so I'll open them in a few days 🔜

**Comment by kelunik** [comment]
I kind of expected that. :smile: 

Maybe you can fix your e-mail in the meantime so it properly links the commit with your account. :+1:

**Comment by maxmeijer42** [comment]
I didn't notice that, thanks!

**Pull request closed without merging**
