### PR TITLE
Add support for accepting larger bodies

### PR DESCRIPTION
**Pull request by bwoebi**
Review please and parseBody() should have some incremental parsing mechanism (TODO).

\ping @kelunik

### CODE REVIEW

**Comment by bwoebi** [comment]
Do not merge yet (tests are failing because of Artax bug)

Also, https://github.com/amphp/aerys/pull/84/files#diff-c6efd2089538af142c51173ed102200eR170 needs fixing … just not sure how to solve yet.

**Comment by bwoebi** [comment]
Ready to merge now.

@kelunik Any API suggestions or is it fine as is?

**Comment by kelunik** [comment]
Don't have time to have a deeper look at it right now.

**Comment by bwoebi** [comment]
Merged via e369f97719b256468a6a4de600c8b3a87e3a2de8

**Pull request closed without merging**
